[versions]
adjustAndroid = "5.0.1"
agp = "8.2.1"
kotlin = "2.0.21-RC"

[libraries]
adjust-android = { module = "com.adjust.sdk:adjust-android", version.ref = "adjustAndroid" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
spm = { id = "io.github.luca992.multiplatform-swiftpackage", version = "2.2.3" }
